databases:
  - name: signal_fire
    databaseName: signal_fire
    user: signal_fire
    plan: free
    region: virginia

services:
  - type: web
    name: signal-fire
    runtime: ruby
    plan: free
    region: virginia
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails assets:clean
    # preDeployCommand is not supported in the free plan, so we will run migrations and seeds as part of the build command.
    # In a production environment, we will want to run these commands separately to avoid downtime during deployment.
    # preDeployCommand: bundle exec rails db:migrate && bundle exec rails db:seed
    startCommand: bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails server -p $PORT -e $RAILS_ENV
    healthCheckPath: /about
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: signal_fire
          property: connectionString
